### ISSUE TITLE
有什么咒语可以减少它的胡编乱造和张冠李戴

### ISSUE THREAD

**Issue by InitialXKO** [howl-anderson/unlocking-the-power-of-llms#5]
比如说有时候要它讲某个历史事件，它会煞有介事地把孟尝君说成蜀国国君，击败了秦国的木流牛马，取得了中原的统治权。还引用李白的《蜀道难》“无边落木萧萧下，不尽长江滚滚来”。

**Comment by Minority2310** [comment]
> 比如说有时候要它讲某个历史事件，它会煞有介事地把孟尝君说成蜀国国君，击败了秦国的木流牛马，取得了中原的统治权。还引用李白的《蜀道难》“无边落木萧萧下，不尽长江滚滚来”。

chatgpt 应该是不擅长汉语中的文言文和古诗之类的内容，毕竟中文语料占比很小，文言古诗占比估计更小~

**Comment by howl-anderson** [comment]
你可以要求它的回复清晰且准确，如果不知道就回复不知道，一定程度能降低这一问题
